### PR TITLE
Rich Object Class

### PR DESCRIPTION
**Pull request by whereisciao**
# This Pull Request is not ready to be pulled

The next goal is to create Rich Data Objects. With all the responses from Surveygizmo wrapped in an object, we will be able to add functionality to manipulate the data as the business needs.

A few details to take note.

The functions `object_from_response` and soon `collection_from_response` are the two functions that converts a request into an object. Another eventual goal is to create some sugar syntax for pagination. 

Next, all endpoints will have a class. Below is an example of the Account class.

```
module Surveygizmo
  class Account < Surveygizmo::Identity
    include Surveygizmo::Creatable
    attr_reader :organization, :contact_phone, :resellers_customer_id, :reseller_uuid

    def login_link
      @login_link ||= CGI.unescape(@attrs[:login_link]) unless @attrs[:login_link].nil?
    end

    def reseller
      @attrs[:reseller]
    end
  end
end
```

This is open for discussion. My plans are to define all the endpoints them move to refactoring errors.

### CODE REVIEW

**Comment by whereisciao** [comment]
Well aware of the failures on the `Error` and `Response`.

**Comment by whereisciao** [comment]
@uhlenbrock What would be process for getting this massive PR reviewed? All existing endpoints will return their respective objects.

**Comment by uhlenbrock** [comment]
First of all, thanks for taking the time and effort to do this @whereisciao! I need some time to discuss with my team and review all 68 commits (:feelsgood:). I will follow-up soon.

**Comment by uhlenbrock** [comment]
I am unable to retrieve live data from SG with this code. 

```
s = Surveygizmo.surveys # => LoadError: cannot load such file -- { JSON DATA }
```

It looks like you are trying to dynamically instantiate a class, but instead of a class name, it is passing in the actual JSON data.

**Comment by whereisciao** [comment]
@uhlenbrock Could you write a test to recreate it? I'm having issues raising the error with my live code. This is the line that dynamically instantiates the class per requests.

https://github.com/whereisciao/surveygizmo/blob/rich_object_class/lib/surveygizmo/client/survey.rb#L16

```
      def surveys(options = {})
        collection_from_response(Surveygizmo::Survey, :get, "survey", options)
      end
```

I'm going to submit another commit because I'm worried the request failed.

**Comment by whereisciao** [comment]
The other place I can think of that parses JSON is [parse_json.rb](https://github.com/whereisciao/surveygizmo/blob/rich_object_class/lib/surveygizmo/response/parse_json.rb). With 6ef6884 errors such as Invalid Credentials or something else will be raised.

```
s = Surveygizmo.surveys # => Surveygizmo::Error::UnknownError: Invalid Credentials
```

**Comment by uhlenbrock** [comment]
Here's a full stack trace:

```
s = Surveygizmo.survey 992278
LoadError: cannot load such file -- {"result_ok":true,"data":{[]}}}

from /gems/activesupport-3.2.0.rc2/lib/active_support/dependencies.rb:245:in `load'
from /gems/activesupport-3.2.0.rc2/lib/active_support/dependencies.rb:245:in `block in load'
from /gems/activesupport-3.2.0.rc2/lib/active_support/dependencies.rb:236:in `load_dependency'
from /gems/activesupport-3.2.0.rc2/lib/active_support/dependencies.rb:245:in `load'
from /surveygizmo/lib/surveygizmo/response/parse_json.rb:9:in `parse'
from /surveygizmo/lib/surveygizmo/response/parse_json.rb:14:in `on_complete'
from /gems/faraday-0.7.5/lib/faraday/response.rb:9:in `block in call'
from /gems/faraday-0.7.5/lib/faraday/response.rb:62:in `on_complete'
from /gems/faraday-0.7.5/lib/faraday/response.rb:8:in `call'
from /gems/faraday-0.7.5/lib/faraday/response.rb:8:in `call'
from /gems/faraday-0.7.5/lib/faraday/request/url_encoded.rb:14:in `call'
from /gems/faraday-0.7.5/lib/faraday/connection.rb:207:in `run_request'
from /gems/faraday-0.7.5/lib/faraday/connection.rb:89:in `get'
from /surveygizmo/lib/surveygizmo/request.rb:25:in `request'
from /surveygizmo/lib/surveygizmo/request.rb:7:in `get'
from /surveygizmo/lib/surveygizmo/api.rb:27:in `object_from_response'
from /surveygizmo/lib/surveygizmo/client/survey.rb:34:in `survey'
from /surveygizmo/lib/surveygizmo.rb:20:in `method_missing'
from (irb):2
from /gems/railties-3.2.0.rc2/lib/rails/commands/console.rb:47:in `start'
from /gems/railties-3.2.0.rc2/lib/rails/commands/console.rb:8:in `start'
from /gems/railties-3.2.0.rc2/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by moretea** [comment]
@whereisciao first of all: kudo's for your effort. It is the way we should go.

Hmm, but this is quite a lot of code. @whereisciao what do you think about trying to break this big pull request into separate, smaller pull requests?

@uhlenbrock @whereisciao Maybe we can talk about this, and talk about the general direction of this gem in a separate issue / chatbox?

**Comment by whereisciao** [comment]
@uhlenbrock My attempts to recreate your issue has failed. There is still one more thing I would like to try now that I have response. 

@moretea Smaller Pull Requests sounds like a good idea as is your suggestions. I'll let @uhlenbrock chime in to see what his thoughts are.

**Comment by uhlenbrock** [comment]
I was able to nail down the version of multi_json as the culprit. Upgrading to 1.3.6 seems to fix the issue.

I also like @moretea's proposed refactorings.

**Comment by moretea** [comment]
I've created a new issue #16, which continues our discussion about the small pull requests.

**Comment by whereisciao** [comment]
Closing this PR as its so old.

**Pull request closed without merging**
